### ISSUE TITLE
network compatibility?

### ISSUE THREAD

**Issue by 17lwinn** [bengarrett/DOSee#7]
can we use the dosbox.conf file to configure ipx, if so where do i put it?

**Comment by bengarrett** [comment]
Hi, sorry for the late response. DOSee doesn't support a `dosbox.conf` or networking.

Alternatively [js-dos](https://github.com/caiiiycuk/js-dos) is an expanded DOSBox API based on the same core that does support `dosbox.conf` like configurations. But I don't believe there is a working ipx implementation there either. 

There is an open PR for networking support in [em-dosbox](https://github.com/dreamlayers/em-dosbox/pull/58/commits).
