### ISSUE TITLE
[REQUEST] Is there a way to controller support?

### ISSUE THREAD

**Issue by technofox01** [bengarrett/DOSee#82]
Hi again,

I am trying to get controller support working. Is this a feature that is available, and if so, how can I enable it or get it work?

I appreciate your help :-)

**Comment by bengarrett** [comment]
Hi, you may wish to fork this project and attempt to hack in support yourself. DOSee is based off emularity which has controller support.
https://github.com/db48x/emularity/blob/master/loader.js

Otherwise, maybe switch to https://js-dos.com ?

**Comment by bengarrett** [comment]
A hacked implementation of controller support has been added, it uses the control to mimic keyboard keys, thanks.
